version: "3.8"

services:
  mongodb:
    image: mongo:4.4.6
    container_name: area-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?err}
    ports:
      - ${AREA_MONGO_PORT:?err}:${AREA_MONGO_PORT:?err}

  area-server:
    build: server
    command: node server.js
    container_name: area-server
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${AREA_SERVER_PORT:?err}:3000
    depends_on:
      - mongodb

  area-web-client:
    build: client/web
    container_name: area-web-client
    volumes:
      - ./client/web:/usr/src/app
    ports:
      - ${AREA_WEB_CLIENT_PORT:?err}:3000
    depends_on:
      - area-server

  area-app-client:
    build: client/app
    container_name: area-app-client
    volumes:
      - ./client/app:/usr/src/app
    environment:
      EXPO_TOKEN: ${EXPO_TOKEN:?err}

