version: "3.7"
services:
#  server:
#    build: server/
#    image: server:tag
#    container_name: server
#    command: "node index.js"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - "mongo"
#
#  mongo:
#    image: "mongo"
#    container_name: mongo
#    ports:
#      - "27017:27017"

  client_mobile:
    build: client/app/
    image: client_mobile:tag
    container_name: client_mobile
    command: "flutter build apk"

#  client_web:
#    build: client/web/
#    image: client_web:tag
#    container_name: client_web
#    command: "npm run dev --port 8081"
#    ports:
#      - "8081:8081"
#    environment:
#      - NODE_ENV=development
#      - PORT=8081
#      - HOST=0.0.0.0
