version: ^3.8

services:
  mongodb:
    image: mongo:4.4.6
    container_name: area-mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017

  area-server:
    build: server
    container_name: area-server
    env_file:
      - .env
    ports:
      - ${AREA_SERVER_PORT}:${AREA_SERVER_PORT}
    depends_on:
      - mongodb

  area-web-client:
    build: client/web
    container_name: area-web-client
    env_file:
      - .env
    volumes:
      - ./client/web:/usr/src/app
    ports:
      - ${AREA_WEB_CLIENT_PORT}:${AREA_WEB_CLIENT_PORT}
    depends_on:
      - area-server
